sudo: required
services:
  - docker
before_install:
  - docker build -t klc215/learn-docker-react -f Dockerfile.dev .
script:
  - docker run klc215/learn-docker-react npm run test -- --coverage --watchAll=false
